# Generated by Django 4.0.6 on 2022-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potterheads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
    ]
